
// This file has been generated by the GUI designer. Do not modify.
namespace GCMM
{
	public partial class MusicAndNowPlayingWidget
	{
		private global::Gtk.HPaned hpaned;
		private global::Gtk.VPaned vpaned2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView GenreNodeView;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.NodeView ArtistNodeView;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.NodeView AlbumNodeView;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.NodeView MusicNodeView;
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		private global::Gtk.NodeView NowPlayingNodeView;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GCMM.MusicAndNowPlayingWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GCMM.MusicAndNowPlayingWidget";
			// Container child GCMM.MusicAndNowPlayingWidget.Gtk.Container+ContainerChild
			this.hpaned = new global::Gtk.HPaned ();
			this.hpaned.CanFocus = true;
			this.hpaned.Name = "hpaned";
			this.hpaned.Position = 599;
			// Container child hpaned.Gtk.Paned+PanedChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 200;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.GenreNodeView = new global::Gtk.NodeView ();
			this.GenreNodeView.CanFocus = true;
			this.GenreNodeView.Name = "GenreNodeView";
			this.GtkScrolledWindow.Add (this.GenreNodeView);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ArtistNodeView = new global::Gtk.NodeView ();
			this.ArtistNodeView.CanFocus = true;
			this.ArtistNodeView.Name = "ArtistNodeView";
			this.GtkScrolledWindow1.Add (this.ArtistNodeView);
			this.hbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow1]));
			w4.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.AlbumNodeView = new global::Gtk.NodeView ();
			this.AlbumNodeView.CanFocus = true;
			this.AlbumNodeView.Name = "AlbumNodeView";
			this.GtkScrolledWindow2.Add (this.AlbumNodeView);
			this.hbox2.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow2]));
			w6.Position = 2;
			this.vpaned2.Add (this.hbox2);
			global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.hbox2]));
			w7.Resize = false;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.MusicNodeView = new global::Gtk.NodeView ();
			this.MusicNodeView.CanFocus = true;
			this.MusicNodeView.Name = "MusicNodeView";
			this.GtkScrolledWindow3.Add (this.MusicNodeView);
			this.vpaned2.Add (this.GtkScrolledWindow3);
			this.hpaned.Add (this.vpaned2);
			global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.hpaned [this.vpaned2]));
			w10.Resize = false;
			// Container child hpaned.Gtk.Paned+PanedChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.WidthRequest = 100;
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.NowPlayingNodeView = new global::Gtk.NodeView ();
			this.NowPlayingNodeView.CanFocus = true;
			this.NowPlayingNodeView.Name = "NowPlayingNodeView";
			this.GtkScrolledWindow4.Add (this.NowPlayingNodeView);
			this.hpaned.Add (this.GtkScrolledWindow4);
			global::Gtk.Paned.PanedChild w12 = ((global::Gtk.Paned.PanedChild)(this.hpaned [this.GtkScrolledWindow4]));
			w12.Resize = false;
			this.Add (this.hpaned);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
